server:
  servlet:
    context-path: "/timesheet/api"
spring:
  application:
    name: Vibbra Timesheet
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5551/vibbra
    platform: postgres
    username: vibbra
    password: vibbra
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
security:
  jwt:
    secret: utYvcV0mYXywgmzj
    expirationTime: 600000
  cipher:
    key: 0z9A0hv/jZfN4csX
    algorithm:  AES
    operationMode: ECB
    paddingScheme: PKCS5Padding